name = "christmas-tree"
main = "worker.js"
compatibility_date = "2024-01-01"

[assets]
directory = "./public"

# D1 database
[[d1_databases]]
binding = "DB"
database_name = "brimtech_controller"
database_id = "6c201d6b-f0dc-4591-8bff-163b98fd05e5"

[vars]
TOKEN = "BtC_92fA7xP14_QmZ87Lw3vS4nHk"

# KV namespace for comenzi brad
[[kv_namespaces]]
binding = "BRAD_KV"
id = "04b4e5fbaaa54a6e94d56d761e1362fa"
